openapi: 3.2.0
info:
  description: This is the public REST API to integrate with the demisto server.
  title: Demisto Statistics API
  version: 2.0.0
servers:
- url: https://hostname:443
security:
- api_key: []
- csrf_token: []
- x-xdr-auth-id: []
tags:
- name: Statistics
paths:
  /statistics/dashboards/query:
    post:
      description: Get a given dashboard statistics result.
      summary: Get Dashboard Statistics
      operationId: GetStatsForDashboard
      responses:
        '200':
          description: Return an array of stats results for each widget cell in dashboard.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StatsQueryResponse'
      tags:
      - Statistics
  /statistics/widgets/query:
    post:
      description: 'Get a given widget object statistics result.

        Note: This route has many return types based on the widget type and data. Each 200X represent a 200 OK request of specific widget type and data'
      summary: Get Widget Statistics
      operationId: getStatsForWidget
      responses:
        '200':
          description: "Response differ according to the widget type\n  -  Incident data type of a \"table\" or \"list\" widget returns incidentSearchResponse\n     total:\n       type: integer\n       data:\n         type: array\n      items:\n        \"$ref\": \"#/definitions/Incident\"\n    - Indicators data type of a \"table\" or \"list\" widget returns IoCsResponse\n      total:\n        type: integer\n      data:\n        type: array\n        items:\n          \"$ref\": \"#/definitions/IocObject\"\n    - Number widget returns a simple number\n      type: integer\n    - Trend widget returns a trend object\n      \"$ref\": \"#/definitions/StatsTrendsResponse\"\n    - Text widget returns a text object, describing the final text and the placeholders values.\n      \"$ref\": \"#/definitions/StatsTextResponse\"\n    - A chart data array by groups. When requesting a date, the key is the date string, according to the specified time frame. Empty groups (dates) are also returned.\n      type: array\n      items:\n        \"$ref\": \"#/definitions/Group\""
          content:
            application/json:
              schema:
                type: object
      tags:
      - Statistics
components:
  schemas:
    StatsQueryResponse:
      type: object
      title: StatsQueryResponse - Describe the data returned related to a specific widget cell in a dashboard.
      properties:
        data:
          description: data array or object describing the statistics data based on type.
          type: object
          x-go-name: Data
        widgetCellId:
          type: string
          x-go-name: WidgetCellID
      x-go-package: github.com/demisto/server/repo/entities
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
    csrf_token:
      type: apiKey
      name: X-XSRF-TOKEN
      in: header
    x-xdr-auth-id:
      type: apiKey
      name: x-xdr-auth-id
      in: header
