openapi: 3.2.0
info:
  description: This is the public REST API to integrate with the demisto server.
  title: Demisto Apikeys API
  version: 2.0.0
servers:
- url: https://hostname:443
security:
- api_key: []
- csrf_token: []
- x-xdr-auth-id: []
tags:
- name: API Keys
paths:
  /apikeys/revoke/user/{username}:
    post:
      description: Revoke API Key for user
      operationId: revokeUserAPIKey
      parameters:
      - description: The username which the API keys assigned to
        name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 200 for success
      tags:
      - API Keys
      summary: Revoke user API key
      x-summary-source: derived
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
    csrf_token:
      type: apiKey
      name: X-XSRF-TOKEN
      in: header
    x-xdr-auth-id:
      type: apiKey
      name: x-xdr-auth-id
      in: header
