openapi: 3.2.0
info:
  description: This is the public REST API to integrate with the demisto server.
  title: Demisto Layouts API
  version: 2.0.0
servers:
- url: https://hostname:443
security:
- api_key: []
- csrf_token: []
- x-xdr-auth-id: []
tags:
- name: Layouts
paths:
  /v2/layouts/import:
    post:
      description: Import a layout to Cortex XSOAR
      summary: Import a layout
      operationId: importLayout
      responses:
        '200':
          description: The saved layout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LayoutAPI'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: file
                  format: binary
                type:
                  type: string
                  description: associated typeID for the layout
                kind:
                  type: string
                  description: layout kind details
              required:
              - file
              - type
              - kind
      tags:
      - Layouts
components:
  schemas:
    LayoutAPI:
      description: 'LayoutAPI - request sent from the client contains some or all

        of the fields.'
      type: object
      properties:
        kind:
          type: string
          x-go-name: Kind
        layout:
          $ref: '#/components/schemas/Layout'
        typeId:
          type: string
          x-go-name: TypeID
      x-go-package: github.com/demisto/server/domain
    Layout:
      type: object
      title: Layout ...
      properties:
        commitMessage:
          type: string
          x-go-name: CommitMessage
        fromServerVersion:
          $ref: '#/components/schemas/Version'
        id:
          type: string
          x-go-name: ID
        itemVersion:
          $ref: '#/components/schemas/Version'
        kind:
          type: string
          x-go-name: Kind
        modified:
          type: string
          format: date-time
          x-go-name: Modified
        name:
          type: string
          x-go-name: Name
        packID:
          type: string
          x-go-name: PackID
        prevKind:
          type: string
          x-go-name: PrevKind
        prevTypeId:
          type: string
          x-go-name: PrevTypeID
        primaryTerm:
          type: integer
          format: int64
          x-go-name: PrimaryTerm
        propagationLabels:
          type: array
          items:
            type: string
          x-go-name: PropagationLabels
        sections:
          type: array
          items:
            $ref: '#/components/schemas/LayoutSection'
          x-go-name: Sections
        sequenceNumber:
          type: integer
          format: int64
          x-go-name: SeqNum
        shouldCommit:
          type: boolean
          x-go-name: ShouldCommit
        sortValues:
          type: array
          items:
            type: string
          x-go-name: SortValues
        system:
          type: boolean
          x-go-name: System
        toServerVersion:
          $ref: '#/components/schemas/Version'
        typeId:
          type: string
          x-go-name: TypeID
        vcShouldIgnore:
          type: boolean
          x-go-name: VCShouldIgnore
        version:
          type: integer
          format: int64
          x-go-name: Versn
      x-go-package: github.com/demisto/server/domain
    Version:
      type: object
      title: Version represents a version.
      properties:
        Digits:
          type: array
          items:
            type: integer
            format: int64
        Label:
          type: string
      x-go-package: github.com/demisto/server/domain
    LayoutSection:
      type: object
      title: LayoutSection ...
      properties:
        description:
          type: string
          x-go-name: Description
        fields:
          type: array
          items:
            $ref: '#/components/schemas/LayoutField'
          x-go-name: Fields
        id:
          type: string
          x-go-name: ID
        isVisible:
          type: boolean
          x-go-name: IsVisible
        modified:
          type: string
          format: date-time
          x-go-name: Modified
        name:
          type: string
          x-go-name: Name
        primaryTerm:
          type: integer
          format: int64
          x-go-name: PrimaryTerm
        query:
          type: object
          x-go-name: Query
        queryType:
          type: string
          x-go-name: QueryType
        readOnly:
          type: boolean
          x-go-name: IsReadOnly
        sequenceNumber:
          type: integer
          format: int64
          x-go-name: SeqNum
        sortValues:
          type: array
          items:
            type: string
          x-go-name: SortValues
        type:
          type: string
          x-go-name: Type
        version:
          type: integer
          format: int64
          x-go-name: Versn
      x-go-package: github.com/demisto/server/domain
    LayoutField:
      type: object
      title: LayoutField ...
      properties:
        fieldId:
          type: string
          x-go-name: FieldID
        id:
          type: string
          x-go-name: ID
        isVisible:
          type: boolean
          x-go-name: IsVisible
        modified:
          type: string
          format: date-time
          x-go-name: Modified
        primaryTerm:
          type: integer
          format: int64
          x-go-name: PrimaryTerm
        sequenceNumber:
          type: integer
          format: int64
          x-go-name: SeqNum
        sortValues:
          type: array
          items:
            type: string
          x-go-name: SortValues
        version:
          type: integer
          format: int64
          x-go-name: Versn
      x-go-package: github.com/demisto/server/domain
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
    csrf_token:
      type: apiKey
      name: X-XSRF-TOKEN
      in: header
    x-xdr-auth-id:
      type: apiKey
      name: x-xdr-auth-id
      in: header
