openapi: 3.2.0
info:
  description: This is the public REST API to integrate with the demisto server.
  title: Demisto Reputation API
  version: 2.0.0
servers:
- url: https://hostname:443
security:
- api_key: []
- csrf_token: []
- x-xdr-auth-id: []
tags:
- name: Reputation
paths:
  /reputation/import:
    post:
      description: Import a reputation type to XSOAR
      summary: Import a reputation type
      operationId: importReputationHandler
      responses:
        '200':
          description: The saved reputation type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reputationsWithErrors'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: file
                  format: binary
              required:
              - file
      tags:
      - Reputation
components:
  schemas:
    Reputation:
      description: This struct is store in the BOLT data store and not indexed into bleve
      type: object
      title: Reputation holds information about the reputation of the entry contents.
      properties:
        cacheVersn:
          type: integer
          format: int64
          x-go-name: CacheVersn
        commitMessage:
          type: string
          x-go-name: CommitMessage
        contextPath:
          type: string
          x-go-name: ContextPath
        contextValue:
          type: string
          x-go-name: ContextValue
        defaultMapping:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AdvanceArg'
          x-go-name: DefaultMapping
        definitionId:
          type: string
          x-go-name: DefinitionID
        details:
          type: string
          x-go-name: Details
        disabled:
          type: boolean
          x-go-name: Disabled
        enhancementScriptNames:
          type: array
          items:
            type: string
          x-go-name: EnhancementScriptNames
        excludedBrands:
          type: array
          items:
            type: string
          x-go-name: ExcludedBrands
        expiration:
          type: integer
          format: int64
          x-go-name: ExpirationInMinutes
        file:
          type: boolean
          x-go-name: FileReputation
        fileHashesPriority:
          type: array
          items:
            type: string
          x-go-name: FileHashesPriority
        formatScript:
          type: string
          x-go-name: FormatScript
        fromServerVersion:
          $ref: '#/components/schemas/Version'
        highlight:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          x-go-name: Highlight
        id:
          type: string
          x-go-name: ID
        itemVersion:
          $ref: '#/components/schemas/Version'
        layout:
          type: string
          x-go-name: Layout
        legacyNames:
          type: array
          items:
            type: string
          x-go-name: LegacyNames
        locked:
          type: boolean
          x-go-name: Locked
        manualMapping:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AdvanceArg'
          x-go-name: ManualMapping
        mergeContext:
          type: boolean
          x-go-name: MergeContext
        modified:
          type: string
          format: date-time
          x-go-name: Modified
        numericId:
          type: integer
          format: int64
          x-go-name: NumericID
        packID:
          type: string
          x-go-name: PackID
        packName:
          type: string
          x-go-name: PackName
        packPropagationLabels:
          type: array
          items:
            type: string
          x-go-name: PackPropagationLabels
        prevDetails:
          type: string
          x-go-name: PrevDetails
        primaryTerm:
          type: integer
          format: int64
          x-go-name: PrimaryTerm
        propagationLabels:
          type: array
          items:
            type: string
          x-go-name: PropagationLabels
        regex:
          type: string
          x-go-name: Regex
        remote:
          type: boolean
          x-go-name: Remote
        reputationCommand:
          type: string
          x-go-name: ReputationCommand
        reputationScriptName:
          type: string
          x-go-name: ReputationScriptName
        sequenceNumber:
          type: integer
          format: int64
          x-go-name: SeqNum
        shouldCommit:
          type: boolean
          x-go-name: ShouldCommit
        shouldShareComments:
          type: boolean
          x-go-name: ShouldShareComments
        sortValues:
          type: array
          items:
            type: string
          x-go-name: SortValues
        syncHash:
          type: string
          x-go-name: SyncHash
        system:
          type: boolean
          x-go-name: System
        toServerVersion:
          $ref: '#/components/schemas/Version'
        updateAfter:
          type: integer
          format: int64
          x-go-name: UpdateAfter
        vcShouldIgnore:
          type: boolean
          x-go-name: VCShouldIgnore
        vcShouldKeepItemLegacyProdMachine:
          type: boolean
          x-go-name: VCShouldKeepItemLegacyProdMachine
        version:
          type: integer
          format: int64
          x-go-name: Versn
      x-go-package: github.com/demisto/server/domain
    OperatorArgument:
      type: object
      title: OperatorArgument ...
      properties:
        isContext:
          type: boolean
          x-go-name: IsContext
        value:
          $ref: '#/components/schemas/AdvanceArg'
      x-go-package: github.com/demisto/server/domain
    AdvanceArg:
      description: 'Simple: plain text such as "hello" (constant) or ${File.ID} (DT expression)

        Complex: struct with all info that is necessary to compute argument value from context (Root, Filters, Accessor & Transformers)'
      type: object
      title: 'AdvanceArg - advance argument can be one of the following:'
      properties:
        complex:
          $ref: '#/components/schemas/ComplexArg'
        simple:
          type: string
          x-go-name: Simple
      x-go-package: github.com/demisto/server/domain
    ArgFilter:
      description: ArgFilter - represent a slice of atomic filters with OR condition between them (e.i. - atomic1 OR atomic2 OR ...)
      type: array
      items:
        $ref: '#/components/schemas/ArgAtomicFilter'
      x-go-package: github.com/demisto/server/domain
    ArgTransformer:
      type: object
      title: ArgTransformer ...
      properties:
        args:
          x-go-name: Args
        operator:
          $ref: '#/components/schemas/TransformerOperatorID'
      x-go-package: github.com/demisto/server/domain
    ArgAtomicFilter:
      description: ArgAtomicFilter - operator with two sides that return true/false
      type: object
      properties:
        ignoreCase:
          type: boolean
          x-go-name: IgnoreCase
        left:
          $ref: '#/components/schemas/OperatorArgument'
        operator:
          $ref: '#/components/schemas/FilterOperatorID'
        right:
          $ref: '#/components/schemas/OperatorArgument'
        type:
          type: string
          x-go-name: Type
      x-go-package: github.com/demisto/server/domain
    Version:
      type: object
      title: Version represents a version.
      properties:
        Digits:
          type: array
          items:
            type: integer
            format: int64
        Label:
          type: string
      x-go-package: github.com/demisto/server/domain
    ComplexArg:
      description: 'ComplexArg - all info that is necessary to compute argument value from context

        Root - the root slice (or object) from to work against

        Filters - a slice of filters to apply to the root object, one after another (e.i. with AND condition between each one)

        Accessor - the key to access to each result after filter

        Transformers - a slice to transformers to apply on the result of the accessed key from each result

        e.g. if user want to take from context all File.DisplayName where File.Extension is ''EXE'', and the result in uppercase than:

        Root: is "File"

        Filters: will hold the "File.DisplayName where File.Extension is ''EXE''" query

        Accessor: is "DisplayName"

        Transformers: will hold the uppercase transformation'
      type: object
      properties:
        accessor:
          type: string
          x-go-name: Accessor
        filters:
          type: array
          items:
            $ref: '#/components/schemas/ArgFilter'
          x-go-name: Filters
        root:
          type: string
          x-go-name: Root
        transformers:
          type: array
          items:
            $ref: '#/components/schemas/ArgTransformer'
          x-go-name: Transformers
      x-go-package: github.com/demisto/server/domain
    TransformerOperatorID:
      type: string
      title: TransformerOperatorID ...
      x-go-package: github.com/demisto/server/domain
    reputationsWithErrors:
      type: object
      properties:
        error:
          type: string
          x-go-name: Error
        reputations:
          type: array
          items:
            $ref: '#/components/schemas/Reputation'
          x-go-name: Reputations
      x-go-package: github.com/demisto/server/web
    FilterOperatorID:
      type: string
      title: FilterOperatorID ...
      x-go-package: github.com/demisto/server/domain
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
    csrf_token:
      type: apiKey
      name: X-XSRF-TOKEN
      in: header
    x-xdr-auth-id:
      type: apiKey
      name: x-xdr-auth-id
      in: header
