openapi: 3.2.0
info:
  description: This is the public REST API to integrate with the demisto server.
  title: Demisto Incidenttypes API
  version: 2.0.0
servers:
- url: https://hostname:443
security:
- api_key: []
- csrf_token: []
- x-xdr-auth-id: []
tags:
- name: Incident Types
paths:
  /incidenttypes/import:
    post:
      description: Import an incident type to Cortex XSOAR
      summary: Import an incident type
      operationId: importIncidentTypesHandler
      responses:
        '200':
          description: The saved incident type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncidentType'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: file
                  format: binary
              required:
              - file
      tags:
      - Incident Types
components:
  schemas:
    ReputationCalcAlg:
      type: number
      format: double
      title: ReputationCalcAlg ...
      x-go-package: github.com/demisto/server/domain
    IncidentType:
      type: object
      title: IncidentType ...
      properties:
        autorun:
          type: boolean
          x-go-name: IsAutoRun
        closureScript:
          type: string
          x-go-name: ClosureScript
        color:
          type: string
          x-go-name: Color
        commitMessage:
          type: string
          x-go-name: CommitMessage
        days:
          type: integer
          format: int64
          x-go-name: Days
        daysR:
          type: integer
          format: int64
          x-go-name: DaysReminder
        default:
          type: boolean
          x-go-name: IsDefaultType
        disabled:
          type: boolean
          x-go-name: Disabled
        hours:
          type: integer
          format: int64
          x-go-name: Hours
        hoursR:
          type: integer
          format: int64
          x-go-name: HoursReminder
        id:
          type: string
          x-go-name: ID
        locked:
          type: boolean
          x-go-name: Locked
        modified:
          type: string
          format: date-time
          x-go-name: Modified
        name:
          type: string
          x-go-name: Name
        playbookId:
          type: string
          x-go-name: PlaybookID
        preProcessingScript:
          type: string
          x-go-name: PreProcessingScript
        prevName:
          type: string
          x-go-name: PrevName
        readonly:
          type: boolean
          x-go-name: ReadOnly
        reputationCalc:
          $ref: '#/components/schemas/ReputationCalcAlg'
        shouldCommit:
          type: boolean
          x-go-name: ShouldCommit
        sla:
          type: integer
          format: int64
          x-go-name: SLA
        slaReminder:
          type: integer
          format: int64
          x-go-name: SLAReminder
        sortValues:
          type: array
          items:
            type: string
          x-go-name: SortValues
        system:
          type: boolean
          x-go-name: System
        vcShouldIgnore:
          type: boolean
          x-go-name: VCShouldIgnore
        version:
          type: integer
          format: int64
          x-go-name: Versn
        weeks:
          type: integer
          format: int64
          x-go-name: Weeks
        weeksR:
          type: integer
          format: int64
          x-go-name: WeeksReminder
      x-go-package: github.com/demisto/server/domain
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
    csrf_token:
      type: apiKey
      name: X-XSRF-TOKEN
      in: header
    x-xdr-auth-id:
      type: apiKey
      name: x-xdr-auth-id
      in: header
