openapi: 3.2.0
info:
  description: This is the public REST API to integrate with the demisto server.
  title: Demisto Contentpacks API
  version: 2.0.0
servers:
- url: https://hostname:443
security:
- api_key: []
- csrf_token: []
- x-xdr-auth-id: []
tags:
- name: Contentpacks
paths:
  /contentpacks/installed/upload:
    post:
      description: Upload a Pack to the marketplace in the Server. Can be used to upload a Pack for an offline scenario or a Pack that hasn't been released.
      summary: Upload a Pack as zip file.
      operationId: uploadContentPacks
      responses:
        '200':
          description: The pack was successfully uploaded
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: file
                  format: binary
                skipValidation:
                  description: if true will skip upload packs validation, use when migrating existing custom content to packs.
                skipVerify:
                  description: If true will skip pack signature verification. Use when uploading a custom or dev pack
              required:
              - file
      tags:
      - Contentpacks
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
    csrf_token:
      type: apiKey
      name: X-XSRF-TOKEN
      in: header
    x-xdr-auth-id:
      type: apiKey
      name: x-xdr-auth-id
      in: header
